config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :login, only: :create
      resources :formulario, only: :create
    end
  end

  resources :usuarios
  resources :filials
  resources :logos, only: [:index, :update]
  devise_for :users
  get "formulario_fields/:id/new" => "formulario_fields#new"
  resources :formulario_fields
  get "formularios/:id/detalhe" => "formularios#detalhe"
  get "formularios/:id/respostas" => "formularios#answers", as: 'answers'

  get "formulario_preenchido/:id/form_enviado" => "formularios#form_enviado"
  get "formulario_preenchido/indexp" =>"formularios#indexp"

  resources :field_types
  root "home#index"
  resources :formularios

end

app/models/formulario.rb
class Formulario < ActiveRecord::Base
  has_many :filial_formularios
  has_many :filials, through: :filial_formularios

  has_many :formulario_fields
  has_many :formulario_ps
  accepts_nested_attributes_for :formulario_fields, allow_destroy: true, :reject_if => lambda { |a| a[:label].blank? }
end

app/controllers/api/v1/formulario_controller.rb
class Api::V1::FormularioController < Api::V1::BaseController

  before_action :authenticate_user, :find_form, :set_fields

  def create
    form_p = FormularioP.create(user: @user, formulario: @form)
    @fields.each do |params_field|
      form_field = FormularioField.find(params_field[:id])

      filled_form = form_p.answers.new(formulario_field: form_field)
      if form_field.file_field?
        filled_form.file = params_field[:valor]
      else
        filled_form.valor = params_field[:valor]
      end

      filled_form.save!
    end

    render json: 'Formulário preenchido com sucesso'

  end

  private

  def formulario_params
    params.permit(:auth_token, :formulario_id, formulario_fields: [:id, :valor])
  end

  def authenticate_user
    @user = User.find_by_auth_token(formulario_params[:auth_token])
    raise ActiveRecord::RecordNotFound, 'Usuário não encontrado' unless @user.present?
  end

  def find_form
    @form = Formulario.find_by_id(formulario_params[:formulario_id])
    raise ActiveRecord::RecordNotFound, 'Formulário não encontrado' unless @form.present?
  end

  def set_fields
    @fields = formulario_params[:formulario_fields]
  end

end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  before_action :set_formulario, only: [:show, :edit, :update, :destroy, :detalhe]

  def form_enviado
    @form = FormularioP.where " formulario_id=?", params[:id]

    # +"<option value='1'>FOTO</option>"
    # +"<option value='2'>VÍDEO</option>"
    # +"<option value='3'>ASSINATURA</option>"
    # +"<option value='4'>COORDENADAS</option>"
    # +"<option value='5'>DATA</option>"
    # +"<option value='6'>DATA HORA</option>"
    # +"<option value='7'>TEXTO</option>"
    # +"<option value='8'>NÚMERO</option>"
    # +"<option value='9'>AUDIO</option>"
    # +"<option value='10'>CHECKBOX</option>"
    # +"<option value='11'>RADIOBOX</option>"
    # +"<option value='12'>ARQUIVO</option>"
    @tipo = ["","Foto","Vídeo","Assinatura","Coordenadas","Data","Data Hora","Texto","Número","Audio","Checkbox","RadioBox","Arquivo"]


  end

  def answers
    form = FormularioP.find(params[:id])
    @answers = form.answers
  end


  def indexp
    @form = Formulario.joins(:formulario_ps).uniq
  end

  # GET /formularios
  # GET /formularios.json
  def index
    @formularios = Formulario.all
  end

  # GET /formularios/1
  # GET /formularios/1.json
  def show
    @fields = FormularioField.where "formulario_id =?", @formulario.id
  end

  # GET /formularios/new
  def new
    @formulario = Formulario.new
    @formulario_field = FormularioField.new
    @fields = FieldType.all
  end

  # GET /formularios/1/edit
  def edit
  end


  # POST /formularios
  # POST /formularios.json
  def create
    @formulario = Formulario.new(formulario_params)

    respond_to do |format|
      if @formulario.save
        format.html { redirect_to @formulario, notice: 'Formulario criado com sucesso.' }
        format.json { render :show, status: :created, location: @formulario }
      else
        format.html { render :new }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formularios/1
  # PATCH/PUT /formularios/1.json
  def update

    form = formulario_params

    respond_to do |format|
      if @formulario.update(formulario_params)
        format.html { redirect_to @formulario, notice: 'Formulario atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @formulario }
      else
        format.html { render :edit }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formularios/1
  # DELETE /formularios/1.json
  def destroy
    @formulario.destroy
    respond_to do |format|
      format.html { redirect_to formularios_url, notice: 'Formulario deletado com sucesso.' }
      format.json { head :no_content }
    end
  end
  def detalhe
    @campos = FormularioField.where "formulario_id = ?", @formulario.id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulario
      @formulario = Formulario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formulario_params

     params.require(:formulario).permit(:nome, filial_ids: [], formulario_fields_attributes: [:id, :label, :field_type_id, :options, :requirido, :_destroy])

      # if params[:tipo] != nil
      # [params.require(:formulario).permit(:nome),
      #  params.require(:tipo).permit!,
      #  params.require(:label).permit!,
      #  params.require(:rec).permit!]
      # else
      #   [params.require(:formulario).permit(:nome),nil,nil,nil]
      # end

    end
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/views/formularios/_form.html.erb
<%= simple_nested_form_for(@formulario) do |f| %>
  <% if @formulario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formulario.errors.count, "error") %> prohibited this formulario from being saved:</h2>

      <ul>
      <% @formulario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :nome, class: "form-control" %>
    <strong>Filiais:</strong>
    <%= f.association :filials, as: :check_boxes, label_method: :nome, value_method: :id, label: false, item_wrapper_class: "checkbox-inline" %>
  </div>
  <hr>
  <%= f.fields_for :formulario_fields do |task_form| %>
    <div class='form-group'>
      <%= task_form.input :label, label: 'Nome do campo', class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= task_form.association :field_type, label_method: :nome, value_method: :id, include_blank: false, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <% if task_form.object.new_record? || task_form.object.options.present? %>
        <%= task_form.input :options, label: 'Opções(separadas por virgulas)', class: 'form-control options_field'%>
      <% else %>
        <%= task_form.input :options, as: :hidden, label: 'Opções(separadas por virgulas)', class: 'form-control options_field'%>
      <% end %>
    </div>

    <div class='form-group'>
      <%= task_form.input :requirido, as: :boolean, label: 'Requerido', checked_value: 1, unchecked_value: 0, class: 'form-control' %>
    </div>
    <%= task_form.link_to_remove "Remover este campo", class: 'btn btn-danger' %>
    <br><hr><br>
  <% end %>
  <p><%= f.link_to_add "Adicionar Campos", :formulario_fields, class: 'btn btn-primary' %></p>

    <br><br><hr>
  <div class="actions">
    <%= f.submit txt , class: "btn btn-success" %>
  </div>

<% end %>

<script type="text/javascript">
  $(document).ready(function () {

    $(document).on('nested:fieldAdded', function(event){
      // this field was just inserted into your form
      var field = event.field;
      var optionsField = field.find('.formulario_formulario_fields_options');
      $(optionsField).hide();

      // it's a jQuery object already! Now you can find date input
      var selectField = field.find('select')
      $(selectField).change(function(){
        if($(this).val() == 10 || $(this).val() == 11){ // or this.value == 'volvo'
          $(optionsField).show();
        } else {
          $(optionsField).hide();
        }
      });
    })
  });
</script>

app/views/formularios/answers.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <h1>Respostas Enviadas</h1>

  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Nome do Campo</th>
      <th>Tipo do Campo</th>
      <th>Valor</th>

    </tr>
    </thead>

    <tbody>
    <% @answers.each do |answer| %>

        <tr>
          <td><%= answer.formulario_field.label %></td>
          <td><%= answer.formulario_field.field_type.nome %></td>
          <td>
            <% if answer.formulario_field.file_field? %>
              <%= link_to 'Ver Arquivo', answer.file.url, class: 'btn btn-primary' %>
            <% else %>
              <%= answer.valor %>
            <% end %>
          </td>




        </tr>
    <% end %>
    </tbody>
  </table>

  <br>



</div>

<div class="widget-foot">

  <%= button_to 'Voltar', formulario_preenchido_indexp_path, method: :get ,class: "btn btn-success" %>
</div>

app/views/formularios/detalhe.html.erb
<div class="padd">

  <h2>Campos do Formulario <%= @formulario.nome %></h2>
<hr>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th width="20%">Label</th>
      <th width="20%">Formulario</th>
      <th width="20%">Tipo</th>
      <th width="20%">Requirido</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody >
    <% if @campos.blank?%>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    <%else%>
        <% @campos.each do |formulario_field| %>
            <tr>
              <td><%= formulario_field.label %></td>
              <td><%= formulario_field.formulario.nome %></td>
              <td><%= formulario_field.field_type.nome %></td>
              <%if formulario_field.requirido == 1%>
                  <td><%= "Requerido" %></td>
              <%else%>
                  <td><%= "Não Requerido" %></td>
              <%end%>
              <td><%= button_to 'Editar', edit_formulario_field_path(formulario_field),method: :get ,class: "btn btn-warning" %></td>
              <td><%= button_to 'Deletar', formulario_field, method: :delete, data: { confirm: 'você tem certeza?' }, class: "btn btn-danger"  %></td>
            </tr>
        <% end %>
    <%end%>
    </tbody>
  </table>
  <% link = "/formulario_fields/"+@formulario.id.to_s+"/new" %>

</div>

<div class="widget-foot">
  <%= button_to 'Adicionar campo ao formulario', url_for(link),method: :get ,class: "btn btn-primary" %>
</div>

app/views/formularios/edit.html.erb
<div class="padd">

  <h2>Editar Formulario</h2>
<hr>
  <%= render partial: 'form' , locals: {txt: "Salvar Edição"}%>



</div>

<div class="widget-foot">
  <%= button_to 'Voltar', formularios_path,method: :get, class: "btn btn-warning" %>
</div>

app/views/formularios/form_enviado.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <h1>Formularios Enviados</h1>

  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Usuário</th>
      <th>Data</th>
    </tr>
    </thead>

    <tbody>
      <% @form.each do |formulario| %>
        <tr>
          <td><%= formulario.user.nome %></td>
          <td><%= formulario.created_at.strftime("%d/%m/%Y") %></td>
          <td><%= link_to 'Ver Formulário', answers_path(formulario.id), class: 'btn btn-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>



</div>

<div class="widget-foot">

  <%= button_to 'Voltar', formulario_preenchido_indexp_path, method: :get ,class: "btn btn-success" %>
</div>

app/views/formularios/index.html.erb
<div class="padd">



  <p id="notice"><%= notice %></p>

  <h2>Formularios Criados</h2>
  <hr>
  <div class="clearfix"></div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th width="70%">Nome</th>
      <th colspan="4"></th>
    </tr>
    </thead>

    <tbody>
    <% @formularios.each do |formulario| %>
        <tr>
          <td><%= formulario.nome %></td>
          <td><%= button_to 'Mostrar', formulario , method: :get ,class: "btn btn-primary"%></td>
          <td><%= button_to 'Editar Formulário', edit_formulario_path(formulario)  , method: :get ,class: "btn btn-primary"%></td>
          <td><%= button_to 'Deletar', formulario, method: :delete, data: { confirm: 'Você tem certeza?' },class: "btn btn-danger" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="clearfix"></div>




</div>

<div class="widget-foot">

  <%= button_to 'Novo Formulario', new_formulario_path, method: :get ,class: "btn btn-success" %>

</div>

app/views/formularios/indexp.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <h1>Formularios Enviados</h1>

  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Nome</th>
      <th>Usuarios</th>
      <th>Filiais</th>
      <th colspan="1"></th>
    </tr>
    </thead>

    <tbody>
    <% if @form.any? %>
      <% @form.each do |formulario| %>
        <% link=formulario.id.to_s+"/form_enviado"%>
        <tr>
          <td><%= formulario.nome %></td>
          <td><%= formulario.formulario_ps.map{|f| f.user.nome}.join(', ') %></td>
          <td><%= formulario.filials.pluck(:nome).join(', ')%></td>
          <td><%= button_to 'Abrir Formulario', url_for(link)  , method: :get ,class: "btn btn-primary"%></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>

  <br>


</div>

<div class="widget-foot">

</div>

app/views/formularios/new.html.erb
<div class="padd">

  <h1>Novo Formulario</h1>

  <%= render partial: 'form', locals: {txt: "Criar Formulario"} %>



</div>

<div class="widget-foot">
  <%= button_to 'Voltar', formularios_path ,method: :get ,class:"btn btn-warning"%>
</div>

app/views/formularios/show.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nome:</strong>
    <%= @formulario.nome %>
    <br>
    <strong>Filials:</strong>
    <%= @formulario.filials.pluck(:nome).join(', ') %>
    <!-- Adiconar tabela de campos -->
  </p>
  <%= button_to 'Editar Formulário', edit_formulario_path(@formulario), method: :get,class: "btn btn-danger" %>
  <hr>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th width="20%">Label</th>
      <th width="20%">Formulario</th>
      <th width="20%">Tipo</th>
      <th width="20%">Requirido</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody >
    <% if @fields.blank?%>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    <%else%>
        <% @fields.each do |formulario_field| %>
            <tr>
              <td><%= formulario_field.label %></td>
              <td><%= formulario_field.formulario.nome %></td>
              <td><%= formulario_field.field_type.nome %></td>
              <%if formulario_field.requirido == 1%>
                  <td><%= "Requerido" %></td>
              <%else%>
                  <td><%= "Não Requerido" %></td>
              <%end%>
              <td><%= button_to 'Deletar', formulario_field, method: :delete, data: { confirm: 'você tem certeza?' }, class: "btn btn-danger"  %></td>
            </tr>
        <% end %>
    <%end%>
    </tbody>
  </table>







<br>


</div>

<div class="widget-foot">



  <%= button_to 'Voltar', formularios_path, method: :get,class: "btn btn-warning" %>

</div>