config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :login, only: :create
      resources :formulario, only: :create
    end
  end

  resources :usuarios
  resources :filials
  resources :logos, only: [:index, :update]
  devise_for :users
  get "formulario_fields/:id/new" => "formulario_fields#new"
  resources :formulario_fields
  get "formularios/:id/detalhe" => "formularios#detalhe"
  get "formularios/:id/respostas" => "formularios#answers", as: 'answers'

  get "formulario_preenchido/:id/form_enviado" => "formularios#form_enviado"
  get "formulario_preenchido/indexp" =>"formularios#indexp"

  resources :field_types
  root "home#index"
  resources :formularios

end

app/models/formulario_field.rb
class FormularioField < ActiveRecord::Base
  belongs_to :field_type
  belongs_to :formulario

  def file_field?
    %w[Foto Vídeo Assinatura Audio Arquivo].include? field_type.nome
  end

end

app/controllers/formulario_fields_controller.rb
class FormularioFieldsController < ApplicationController
  before_action :set_formulario_field, only: [:show, :edit, :update, :destroy]

  # GET /formulario_fields
  # GET /formulario_fields.json
  def index
    @formulario_fields = FormularioField.all
  end

  # GET /formulario_fields/1
  # GET /formulario_fields/1.json
  def show
  end

  # GET /formulario_fields/new
  def new
    if params[:id] != nil
       @form = Formulario.find(params[:id])
    end
    @formulario_field = FormularioField.new
    @fields = FieldType.all
    @formulario = Formulario.all
  end

  # GET /formulario_fields/1/edit
  def edit
  end

  # POST /formulario_fields
  # POST /formulario_fields.json
  def create
    parametros =formulario_field_params
    @formulario_field = FormularioField.new(parametros[0])

    if parametros [1] != nil
      tipo = parametros[1]
      label = parametros[2]
      rec = parametros[3]




      x=0
      for i in tipo

        form = FormularioField.new
        form.formulario_id =parametros[0]["formulario_id"]
        form.label = label[x.to_s]
        form.requirido = rec[x.to_s]
        form.field_type_id =tipo[x.to_s]
        form.save
        x+=1
      end

    end

    respond_to do |format|
      if @formulario_field.save
        format.html { redirect_to @formulario_field, notice: 'Formulario field was successfully created.' }
        format.json { render :show, status: :created, location: @formulario_field }
      else
        format.html { render :new }
        format.json { render json: @formulario_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formulario_fields/1
  # PATCH/PUT /formulario_fields/1.json
  def update
    params = formulario_field_params
    respond_to do |format|
      if @formulario_field.update(params[0])
        format.html { redirect_to @formulario_field, notice: 'Formulario field was successfully updated.' }
        format.json { render :show, status: :ok, location: @formulario_field }
      else
        format.html { render :edit }
        format.json { render json: @formulario_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formulario_fields/1
  # DELETE /formulario_fields/1.json
  def destroy
    @formulario_field.destroy
    respond_to do |format|
      format.html { redirect_to @formulario, notice: 'Formulario field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_formulario_field
    @formulario_field = FormularioField.find(params[:id])
    @formulario = @formulario_field.formulario
    @fields = FieldType.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def formulario_field_params
    if params[:tipo] != nil
      [params.require(:formulario_field).permit(:label, :formulario_id, :field_type_id, :requirido),
       params.require(:tipo).permit!,
       params.require(:label).permit!,
       params.require(:rec).permit!]
    else
      [params.require(:formulario_field).permit(:label, :formulario_id, :field_type_id, :requirido),
       nil,nil,nil]
    end
  end
end

app/helpers/formulario_fields_helper.rb
module FormularioFieldsHelper
end

app/views/formulario_fields/_form.html.erb
<%= form_for(@formulario_field) do |f| %>
  <% if @formulario_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formulario_field.errors.count, "error") %> prohibited this formulario_field from being saved:</h2>

      <ul>
      <% @formulario_field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if @form == nil %>

    <div class="field">
      <%= f.label :formulario_id %><br>
      <%= f.collection_select :formulario_id,@formulario, :id,:nome , class: "selectpickerl"%>
    </div>
    <%else%>

        <div class="field">
          <input type="hidden" id="formulario_field[formulario_id]" name="formulario_field[formulario_id]" value="<%=@form.id %>">
        </div>


     <% end %>
    <hr>


      <div class="form-group">
    <%= f.label "Nome do Campo" %><br>
    <%= f.text_field :label , class: "form-control"%>
  </div>


      <div class="form-group">
    <%= f.label "Tipo do Campo" %><br>
    <%= f.collection_select :field_type_id ,@fields, :id,:nome, class: "selectpicker" %>
  </div>
      <div class="form-group">
    <%= f.label :requirido %><br>
    <select name='formulario_field[requirido]'>
      <option value='1'>Sim
      </option><option value='0'>Não</option>
    </select>
  </div>



    <hr>
    <div id="add"></div>
<br><br>

  <div class="actions">
    <%= f.submit "Criar Campos", class:"btn btn-success" %>
  </div>
<% end %>

<% if txt == "Criar Campos" %>

    <button id="repeat" class="btn btn-primary">Adicionar mais campos</button>


<% end %>

app/views/formulario_fields/edit.html.erb
<div class="padd">

  <h2>Editing Formulario Field</h2>
<hr>
  <%= render partial: 'form' , locals: {txt: "Salvar Edição"} %>
</div>

<div class="widget-foot">

  <%= button_to 'Voltar', formulario_fields_path ,method: :get, class: "btn btn-warning" %>

</div>

app/views/formulario_fields/index.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <h2>Lista de Campos de todos os formularios</h2>
<hr>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th width="20%">Label</th>
      <th width="20%">Formulario</th>
      <th width="20%">Tipo</th>
      <th width="20%">Requirido</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody >
    <% @formulario_fields.each do |formulario_field| %>
        <tr>
          <td><%= formulario_field.label %></td>
          <td><%= formulario_field.formulario.try(:nome) %></td>
          <td><%= formulario_field.field_type.nome %></td>
          <td><%= formulario_field.requirido %></td>
          <td><%= button_to 'Editar', edit_formulario_field_path(formulario_field),class: "btn btn-warning" %></td>
          <td><%= link_to 'Deletar', formulario_field, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>



</div>

<div class="widget-foot">
  <%= button_to 'Adicionar Campo a formulario', new_formulario_field_path, method: :get, class: "btn btn-success" %>
</div>

app/views/formulario_fields/new.html.erb
<div class="padd">

  <% if @form == nil %>
      <h2>Adicionar Campos</h2>
  <% else %>
      <h2>Adicionar Campos <%=@form.nome  %></h2>
  <% end %>
  <hr>
  <%= render partial: 'form' , locals: {txt: "Criar Campos"} %>


</div>

<div class="widget-foot">
  <%= button_to 'Voltar', formulario_fields_path, method: :get, class: "btn btn-warning" %>
</div>

app/views/formulario_fields/show.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Label:</strong>
    <%= @formulario_field.label %>
  </p>

  <p>
    <strong>Formulario:</strong>
    <%= @formulario_field.formulario_id %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= @formulario_field.field_type_id %>
  </p>

  <p>
    <strong>Requirido:</strong>
    <%= @formulario_field.requirido %>
  </p>

<br>

  <%= button_to 'Editar', edit_formulario_field_path(@formulario_field), method: :get,class: "btn btn-success" %>
</div>

<div class="widget-foot">
  <%= button_to 'Voltar', formulario_fields_path, method: :get,class: "btn btn-warning" %>
</div>