config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :login, only: :create
      resources :formulario, only: :create
    end
  end

  resources :usuarios
  resources :filials
  resources :logos, only: [:index, :update]
  devise_for :users
  get "formulario_fields/:id/new" => "formulario_fields#new"
  resources :formulario_fields
  get "formularios/:id/detalhe" => "formularios#detalhe"
  get "formularios/:id/respostas" => "formularios#answers", as: 'answers'

  get "formulario_preenchido/:id/form_enviado" => "formularios#form_enviado"
  get "formulario_preenchido/indexp" =>"formularios#indexp"

  resources :field_types
  root "home#index"
  resources :formularios

end

app/models/filial.rb
class Filial < ActiveRecord::Base
  has_many :filial_formularios
  has_many :formularios, through: :filial_formularios
end

app/controllers/filials_controller.rb
class FilialsController < ApplicationController
  before_action :set_filial, only: [:show, :edit, :update, :destroy]

  # GET /filials
  # GET /filials.json
  def index
    @filials = Filial.all
  end

  # GET /filials/1
  # GET /filials/1.json
  def show
  end

  # GET /filials/new
  def new
    @filial = Filial.new
  end

  # GET /filials/1/edit
  def edit
  end

  # POST /filials
  # POST /filials.json
  def create
    @filial = Filial.new(filial_params)

    respond_to do |format|
      if @filial.save
        format.html { redirect_to @filial, notice: 'Filial criada com sucesso.' }
        format.json { render :show, status: :created, location: @filial }
      else
        format.html { render :new }
        format.json { render json: @filial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filials/1
  # PATCH/PUT /filials/1.json
  def update
    respond_to do |format|
      if @filial.update(filial_params)
        format.html { redirect_to @filial, notice: 'Filial atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @filial }
      else
        format.html { render :edit }
        format.json { render json: @filial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filials/1
  # DELETE /filials/1.json
  def destroy
    @filial.destroy
    respond_to do |format|
      format.html { redirect_to filials_url, notice: 'Filial deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filial
      @filial = Filial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filial_params
      params.require(:filial).permit(:nome)
    end
end

app/helpers/filials_helper.rb
module FilialsHelper
end

app/views/filials/_form.html.erb
<%= form_for(@filial) do |f| %>
  <% if @filial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filial.errors.count, "error") %> prohibited this filial from being saved:</h2>

      <ul>
      <% @filial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit txt, class: "btn btn-success"%>
  </div>
<% end %>

app/views/filials/edit.html.erb
<div class="padd">

  <h2>Editar Filial</h2>
<hr>
  <%= render partial: 'form'  , locals: {txt: "Editar Filial"}%>


</div>

<div class="widget-foot">

  <%= button_to 'Voltar', filials_path,method: :get, class: "btn btn-warning" %>
</div>

app/views/filials/index.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <h2>Lista de  Filiais</h2>
<hr>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th width="70%">Nome</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @filials.each do |filial| %>
        <tr>
          <td><%= filial.nome %></td>
          <td><%= button_to 'Mostrar', filial , method: :get ,class: "btn btn-primary"%></td>
          <td><%= button_to 'Editar', edit_filial_path(filial), method: :get ,class: "btn btn-warning" %></td>
          <td><%= button_to 'Deletar', filial, method: :delete, data: { confirm: 'Você tem certeza?' },class: "btn btn-danger" %></td>


        </tr>
    <% end %>
    </tbody>
  </table>

  <br>


</div>

<div class="widget-foot">
  <%= button_to 'Adicionar Filial', new_filial_path, method: :get ,class: "btn btn-success" %>

</div>

app/views/filials/new.html.erb
<div class="padd">
  <h1>Nova Filial</h1>


  <%= render partial: 'form', locals: {txt: "Criar Filial"} %>


</div>

<div class="widget-foot">
  <%= button_to 'Voltar', filials_path ,method: :get ,class:"btn btn-warning"%>
</div>

app/views/filials/show.html.erb
<div class="padd">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nome:</strong>
    <%= @filial.nome %>
  </p>


  <%= button_to 'Editar', edit_filial_path(@filial), method: :get,class: "btn btn-danger" %>

</div>

<div class="widget-foot">
  <%= button_to 'Voltar', filials_path, method: :get,class: "btn btn-warning" %>
</div>