config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :login, only: :create
      resources :formulario, only: :create
    end
  end

  resources :usuarios
  resources :filials
  resources :logos, only: [:index, :update]
  devise_for :users
  get "formulario_fields/:id/new" => "formulario_fields#new"
  resources :formulario_fields
  get "formularios/:id/detalhe" => "formularios#detalhe"
  get "formularios/:id/respostas" => "formularios#answers", as: 'answers'

  get "formulario_preenchido/:id/form_enviado" => "formularios#form_enviado"
  get "formulario_preenchido/indexp" =>"formularios#indexp"

  resources :field_types
  root "home#index"
  resources :formularios

end

app/controllers/field_types_controller.rb
class FieldTypesController < ApplicationController
  before_action :set_field_type, only: [:show, :edit, :update, :destroy]

  # GET /field_types
  # GET /field_types.json
  def index
    @field_types = FieldType.all
  end

  # GET /field_types/1
  # GET /field_types/1.json
  def show
  end

  # GET /field_types/new
  def new
    @field_type = FieldType.new
  end

  # GET /field_types/1/edit
  def edit
  end

  # POST /field_types
  # POST /field_types.json
  def create
    @field_type = FieldType.new(field_type_params)

    respond_to do |format|
      if @field_type.save
        format.html { redirect_to @field_type, notice: 'Campo criado com sucesso.' }
        format.json { render :show, status: :created, location: @field_type }
      else
        format.html { render :new }
        format.json { render json: @field_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /field_types/1
  # PATCH/PUT /field_types/1.json
  def update
    respond_to do |format|
      if @field_type.update(field_type_params)
        format.html { redirect_to @field_type, notice: 'Campo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @field_type }
      else
        format.html { render :edit }
        format.json { render json: @field_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_types/1
  # DELETE /field_types/1.json
  def destroy
    @field_type.destroy
    respond_to do |format|
      format.html { redirect_to field_types_url, notice: 'Campo Deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field_type
      @field_type = FieldType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_type_params
      params.require(:field_type).permit(:nome)
    end
end

app/helpers/field_types_helper.rb
module FieldTypesHelper
end

app/views/field_types/_form.html.erb
<%= form_for(@field_type) do |f| %>
  <% if @field_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field_type.errors.count, "error") %> prohibited this field_type from being saved:</h2>

      <ul>
      <% @field_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/field_types/_form_select.html.erb
oiii

app/views/field_types/edit.html.erb
<h1>Editing Field Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @field_type %> |
<%= link_to 'Back', field_types_path %>

app/views/field_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Field Types</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @field_types.each do |field_type| %>
      <tr>
        <td><%= field_type.nome %></td>
        <td><%= link_to 'Show', field_type %></td>
        <td><%= link_to 'Edit', edit_field_type_path(field_type) %></td>
        <td><%= link_to 'Destroy', field_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field type', new_field_type_path %>

app/views/field_types/new.html.erb
<h1>New Field Type</h1>

<%= render 'form' %>

<%= link_to 'Back', field_types_path %>

app/views/field_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @field_type.nome %>
</p>

<%= link_to 'Edit', edit_field_type_path(@field_type) %> |
<%= link_to 'Back', field_types_path %>